<?php
use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_form_alter().
 */
function booker_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    if ($form_id == 'node_booking_form') {
      // Add the custom validation handler.
      $form['#validate'][] = 'booker_form_validate';
    }
  }

  
/**
 * Custom validation handler for the booking form.
 */
function booker_form_validate(&$form, FormStateInterface $form_state) {
    dpm($form_state);

    // Example validation: Ensure the "email" field is not empty.
    if (empty($form_state->getValue('field_field_start_datetime'))) {
      $form_state->setErrorByName('email', t('The email field is required.'));
    }
}